NarodnyjControl/config/routes.rb
NarodnyjControl::Application.routes.draw do
  resources :claims

  resources :claim_classifiers

  resources :users

  resources :sessions

  resources :api_versions

  post 'api/v1/auth/' => 'api/auth#login'
  delete 'api/v1/auth' => 'api/auth#logout'
  
  post 'api/v1/auth/resetPassword' => 'api/auth#resetPassword'
  post 'api/v1/auth/register' => 'api/auth#register'
  put 'api/v1/auth/' => 'api/auth#update'
  put 'api/v1/auth/settings' => 'api/auth#update_settings'
  

  get "api/v1/:sid/classifiers/(:date)" => 'api/classifiers#get'

  get 'api/v1/:sid/claims/(:date)' => 'api/claims#index'
  post 'api/v1/:sid/claims/' => 'api/claims#create'
  put 'api/v1/:sid/claims/:id' => 'api/claims#update'
  patch 'api/v1/:sid/claims/:id' => 'api/claims#update'
  delete 'api/v1/:sid/claims/:id' => 'api/claims#delete'
  
  get 'api/v1/:sid/attachments/:id/:number/preview' => 'api/attachments#preview'
    
  root 'default#index'

  

end

NarodnyjControl/app/models/claim_classifier.rb
class ClaimClassifier < ActiveRecord::Base
  has_ancestry
end

NarodnyjControl/app/controllers/claim_classifiers_controller.rb
class ClaimClassifiersController < ApplicationController
  before_action :set_claim_classifier, only: [:show, :edit, :update, :destroy]

  # GET /claim_classifiers
  # GET /claim_classifiers.json
  def index
    @claim_classifiers = ClaimClassifier.all
  end

  # GET /claim_classifiers/1
  # GET /claim_classifiers/1.json
  def show
  end

  # GET /claim_classifiers/new
  def new
    @claim_classifier = ClaimClassifier.new(:parent_id => params[:parent_id])
    @claim_classifier["end_date"] = Time.now + 60*60*24*365
  end

  # GET /claim_classifiers/1/edit
  def edit
  end

  # POST /claim_classifiers
  # POST /claim_classifiers.json
  def create
    @claim_classifier = ClaimClassifier.new(claim_classifier_params)

    respond_to do |format|
      if @claim_classifier.save
        format.html { redirect_to @claim_classifier, notice: 'Claim classifier was successfully created.' }
        format.json { render action: 'show', status: :created, location: @claim_classifier }
      else
        format.html { render action: 'new' }
        format.json { render json: @claim_classifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claim_classifiers/1
  # PATCH/PUT /claim_classifiers/1.json
  def update
    respond_to do |format|
      if @claim_classifier.update(claim_classifier_params)
        format.html { redirect_to @claim_classifier, notice: 'Claim classifier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @claim_classifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claim_classifiers/1
  # DELETE /claim_classifiers/1.json
  def destroy
    @claim_classifier.destroy
    respond_to do |format|
      format.html { redirect_to claim_classifiers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim_classifier
      @claim_classifier = ClaimClassifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_classifier_params
      params.require(:claim_classifier).permit(:name, :description, :begin_date, :end_date, :parent_id)
    end
end

NarodnyjControl/app/helpers/claim_classifiers_helper.rb
module ClaimClassifiersHelper
  def nested_claims(claims)
    claims.map do |claim, sub_claims|
      render(claim) + content_tag(:div, nested_claims(sub_claims), :class => "nested_claim")
    end.join.html_safe
  end
end

NarodnyjControl/app/views/claim_classifiers/_claim_classifier.html.erb
<div class="claim">
        <div><%= claim_classifier.name %></div>|
        <div><%= claim_classifier.description %></div>|
        <div><%= claim_classifier.begin_date %></div>|
        <div><%= claim_classifier.end_date %></div>|
        <div><%= link_to 'Show', claim_classifier %></div>|
        <div><%= link_to 'Edit', edit_claim_classifier_path(claim_classifier) %></div>|
        <div><%= link_to 'Destroy', claim_classifier, method: :delete, data: { confirm: 'Are you sure?' } %></div>|
        <div><%= link_to 'Child', new_claim_classifier_path(:parent_id => claim_classifier) %></div>
</div>

NarodnyjControl/app/views/claim_classifiers/_form.html.erb
<%= form_for(@claim_classifier) do |f| %>
  <% if @claim_classifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@claim_classifier.errors.count, "error") %> prohibited this claim_classifier from being saved:</h2>

      <ul>
      <% @claim_classifier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :parent_id %>
	
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :begin_date %><br>
    <%= f.datetime_select :begin_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NarodnyjControl/app/views/claim_classifiers/edit.html.erb
<h1>Editing claim_classifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @claim_classifier %> |
<%= link_to 'Back', claim_classifiers_path %>

NarodnyjControl/app/views/claim_classifiers/index.html.erb
<h1>Listing claim_classifiers</h1>

<%= nested_claims @claim_classifiers.arrange(:order => :created_at) %>

<br>

<%= link_to 'New Claim classifier', new_claim_classifier_path %>

NarodnyjControl/app/views/claim_classifiers/new.html.erb
<h1>New claim_classifier</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Begin date</th>
      <th>End date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @claim_classifier.parent if @claim_classifier.parent %>
  </tbody>
</table>

<%= render 'form' %>

<%= link_to 'Back', claim_classifiers_path %>

NarodnyjControl/app/views/claim_classifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @claim_classifier.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @claim_classifier.description %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @claim_classifier.begin_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @claim_classifier.end_date %>
</p>

<%= link_to 'Edit', edit_claim_classifier_path(@claim_classifier) %> |
<%= link_to 'Back', claim_classifiers_path %>