NarodnyjControl/config/routes.rb
NarodnyjControl::Application.routes.draw do
  resources :claims

  resources :claim_classifiers

  resources :users

  resources :sessions

  resources :api_versions

  post 'api/v1/auth/' => 'api/auth#login'
  delete 'api/v1/auth' => 'api/auth#logout'
  
  post 'api/v1/auth/resetPassword' => 'api/auth#resetPassword'
  post 'api/v1/auth/register' => 'api/auth#register'
  put 'api/v1/auth/' => 'api/auth#update'
  put 'api/v1/auth/settings' => 'api/auth#update_settings'
  

  get "api/v1/:sid/classifiers/(:date)" => 'api/classifiers#get'

  get 'api/v1/:sid/claims/(:date)' => 'api/claims#index'
  post 'api/v1/:sid/claims/' => 'api/claims#create'
  put 'api/v1/:sid/claims/:id' => 'api/claims#update'
  patch 'api/v1/:sid/claims/:id' => 'api/claims#update'
  delete 'api/v1/:sid/claims/:id' => 'api/claims#delete'
  
  get 'api/v1/:sid/attachments/:id/:number/preview' => 'api/attachments#preview'
    
  root 'default#index'

  

end

NarodnyjControl/app/models/api_version.rb
class ApiVersion < ActiveRecord::Base
end

NarodnyjControl/app/controllers/api_versions_controller.rb
class ApiVersionsController < ApplicationController
  before_action :set_api_version, only: [:show, :edit, :update, :destroy]

  # GET /api_versions
  # GET /api_versions.json
  def index
    @api_versions = ApiVersion.all
  end

  # GET /api_versions/1
  # GET /api_versions/1.json
  def show
  end

  # GET /api_versions/new
  def new
    @api_version = ApiVersion.new
  end

  # GET /api_versions/1/edit
  def edit
  end

  # POST /api_versions
  # POST /api_versions.json
  def create
    @api_version = ApiVersion.new(api_version_params)

    respond_to do |format|
      if @api_version.save
        format.html { redirect_to @api_version, notice: 'Api version was successfully created.' }
        format.json { render action: 'show', status: :created, location: @api_version }
      else
        format.html { render action: 'new' }
        format.json { render json: @api_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_versions/1
  # PATCH/PUT /api_versions/1.json
  def update
    respond_to do |format|
      if @api_version.update(api_version_params)
        format.html { redirect_to @api_version, notice: 'Api version was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @api_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_versions/1
  # DELETE /api_versions/1.json
  def destroy
    @api_version.destroy
    respond_to do |format|
      format.html { redirect_to api_versions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_version
      @api_version = ApiVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_version_params
      params.require(:api_version).permit(:version, :uri, :description)
    end
end

NarodnyjControl/app/helpers/api_versions_helper.rb
module ApiVersionsHelper
end

NarodnyjControl/app/views/api_versions/_form.html.erb
<%= form_for(@api_version) do |f| %>
  <% if @api_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_version.errors.count, "error") %> prohibited this api_version from being saved:</h2>

      <ul>
      <% @api_version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :uri %><br>
    <%= f.text_field :uri %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NarodnyjControl/app/views/api_versions/edit.html.erb
<h1>Editing api_version</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_version %> |
<%= link_to 'Back', api_versions_path %>

NarodnyjControl/app/views/api_versions/index.html.erb
<h1>Listing api_versions</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Uri</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @api_versions.each do |api_version| %>
      <tr>
        <td><%= api_version.version %></td>
        <td><%= api_version.uri %></td>
        <td><%= api_version.description %></td>
        <td><%= link_to 'Show', api_version %></td>
        <td><%= link_to 'Edit', edit_api_version_path(api_version) %></td>
        <td><%= link_to 'Destroy', api_version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api version', new_api_version_path %>

NarodnyjControl/app/views/api_versions/new.html.erb
<h1>New api_version</h1>

<%= render 'form' %>

<%= link_to 'Back', api_versions_path %>

NarodnyjControl/app/views/api_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @api_version.version %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @api_version.uri %>
</p>

<p>
  <strong>Description:</strong>
  <%= @api_version.description %>
</p>

<%= link_to 'Edit', edit_api_version_path(@api_version) %> |
<%= link_to 'Back', api_versions_path %>