NarodnyjControl/config/routes.rb
NarodnyjControl::Application.routes.draw do
  resources :claims

  resources :claim_classifiers

  resources :users

  resources :sessions

  resources :api_versions

  post 'api/v1/auth/' => 'api/auth#login'
  delete 'api/v1/auth' => 'api/auth#logout'
  
  post 'api/v1/auth/resetPassword' => 'api/auth#resetPassword'
  post 'api/v1/auth/register' => 'api/auth#register'
  put 'api/v1/auth/' => 'api/auth#update'
  put 'api/v1/auth/settings' => 'api/auth#update_settings'
  

  get "api/v1/:sid/classifiers/(:date)" => 'api/classifiers#get'

  get 'api/v1/:sid/claims/(:date)' => 'api/claims#index'
  post 'api/v1/:sid/claims/' => 'api/claims#create'
  put 'api/v1/:sid/claims/:id' => 'api/claims#update'
  patch 'api/v1/:sid/claims/:id' => 'api/claims#update'
  delete 'api/v1/:sid/claims/:id' => 'api/claims#delete'
  
  get 'api/v1/:sid/attachments/:id/:number/preview' => 'api/attachments#preview'
    
  root 'default#index'

  

end

NarodnyjControl/app/models/claim.rb
class Claim < ActiveRecord::Base
    belongs_to :claim_classifier, :foreign_key => :claim_classifier_id
end

NarodnyjControl/app/controllers/api/claims_controller.rb
require 'json'
class Api::ClaimsController < Api::ApplicationController
  def create
    begin
      Rails.logger.debug params.inspect
      claim_object = JSON.parse(params[:claim])
      claim = Claim.new(claim_params(claim_object))
      claim.originator_id = @session.user_id
      claim.save
      render :json => claim_attributes_to_hash(claim)
    rescue Exception
      render_error('show', 'claim.createError')
    end
  end
  
  def update
    begin
      claim_object = JSON.parse(params[:claim])
      claim.update(claim_params(claim_object))
      render :json => claim_attributes_to_hash(claim)
    rescue Exception
      render_error('show', 'claim.createError')
    end
  end
  
   
  def index
    if (params[:date].nil?)
      claims = Claim.where(['originator_id = ?', @session.user_id]).order('created_at')
    else
      claims = Claim.where(['originator_id = ? and updated_at > ?', @session.user_id, params[:date].gsub('T', ' ')]).order('created_at')
    end
    render :json => claims.map { |c| claim_attributes_to_hash(c) }
  end
  
  private
    def claim_attributes_to_hash(c)
      claim = c.attributes.except('originator_id','creator_id','responsible_id','departament_id', 'registration_no')
      claim['claim_classifier'] = c.claim_classifier.name
      claim['status'] = '[text status here]' #todo:
      claim['attachments'] = [ #todo
        {
          :id => 1,
          :kind => 0,
          :preview => 'attachments/' + c.id.to_s + '/0/preview',
          :original => 'attachments/' + c.id.to_s + '/0/original',
        }
      ]
      return claim    
    end

    def claim_params(claim_object)
      claimHash = claim_object.to_hash
      permitted = ['id', 'title', 'description', 'address', 
        'pos_lat', 'pos_lon', 'pos_alt', 'created_at', 'user_rate', 'user_feedback', 'claim_classifier_id']
      return claimHash.select {|k,v|  permitted.include?(k) }
      end  
  
end

NarodnyjControl/app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  # GET /claims
  # GET /claims.json
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = Claim.new(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render action: 'show', status: :created, location: @claim }
      else
        format.html { render action: 'new' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:originator_id, :title, :description, :category_id, :address, 
      :pos_lat, :pos_lon, :pos_alt, :created_at, :registered_at, :registration_no, :status, :status_code, :deadline, :user_rate, 
      :authority_response, :authority_response_date, :responsible_id, :departament_id, :user_feedback, :claim_classifier_id)
    end
end

NarodnyjControl/app/helpers/api/claims_helper.rb
module Api::ClaimsHelper
end

NarodnyjControl/app/helpers/claims_helper.rb
module ClaimsHelper
end

NarodnyjControl/app/views/claims/_form.html.erb
<%= form_for(@claim) do |f| %>
  <% if @claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
      <% @claim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :originator_id %><br>
    <%= f.number_field :originator_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :pos_lat %><br>
    <%= f.text_field :pos_lat %>
  </div>
  <div class="field">
    <%= f.label :pos_lon %><br>
    <%= f.text_field :pos_lon %>
  </div>
  <div class="field">
    <%= f.label :pos_alt %><br>
    <%= f.text_field :pos_alt %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :registered_at %><br>
    <%= f.datetime_select :registered_at %>
  </div>
  <div class="field">
    <%= f.label :registration_no %><br>
    <%= f.text_field :registration_no %>
  </div>
  <div class="field">
    <%= f.label :responsible_id %><br>
    <%= f.number_field :responsible_id %>
  </div>
  <div class="field">
    <%= f.label :departament_id %><br>
    <%= f.number_field :departament_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :status_code %><br>
    <%= f.text_field :status_code %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :authority_response %><br>
    <%= f.text_area :authority_response %>
  </div>
  <div class="field">
    <%= f.label :authority_response_date %><br>
    <%= f.datetime_select :authority_response_date %>
  </div>
  <div class="field">
    <%= f.label :user_rate %><br>
    <%= f.number_field :user_rate %>
  </div>
  <div class="field">
    <%= f.label :user_feedback %><br>
    <%= f.text_area :user_feedback %>
  </div>
  <%= unless !@claim.claim_classifier.nil? then '<none>' else @claim.claim_classifier.name end %>
   <div class="field">
    <%= f.label :claim_classifier_id %><br>
    <%= f.number_field :claim_classifier_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NarodnyjControl/app/views/claims/edit.html.erb
<h1>Editing claim</h1>

<%= render 'form' %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

NarodnyjControl/app/views/claims/index.html.erb
<h1>Listing claims</h1>

<table>
  <thead>
    <tr>
      <th>Originator</th>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Address</th>
      <th>Pos lat</th>
      <th>Pos lon</th>
      <th>Pos alt</th>
      <th>Created at</th>
      <th>Registered at</th>
      <th>Registration no</th>
      <th>Status</th>
      <th>Status code</th>
      <th>Deadline</th>
      <th>Rate</th>
      <th>Authority response</th>
      <th>Authority response date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= claim.originator_id %></td>
        <td><%= claim.title %></td>
        <td><%= claim.description %></td>
        <td><%= unless !claim.claim_classifier.nil? then '<none>' else claim.claim_classifier.name end %></td>
        <td><%= claim.address %></td>
        <td><%= claim.pos_lat %></td>
        <td><%= claim.pos_lon %></td>
        <td><%= claim.pos_alt %></td>
        <td><%= claim.created_at %></td>
        <td><%= claim.registered_at %></td>
        <td><%= claim.registration_no %></td>
        <td><%= claim.status %></td>
        <td><%= claim.status_code %></td>
        <td><%= claim.deadline %></td>
        <td><%= claim.user_rate %></td>
        <td><%= claim.authority_response %></td>
        <td><%= claim.authority_response_date %></td>
        <td><%= link_to 'Show', claim %></td>
        <td><%= link_to 'Edit', edit_claim_path(claim) %></td>
        <td><%= link_to 'Destroy', claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim', new_claim_path %>

NarodnyjControl/app/views/claims/new.html.erb
<h1>New claim</h1>

<%= render 'form' %>

<%= link_to 'Back', claims_path %>

NarodnyjControl/app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Originator:</strong>
  <%= @claim.originator_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @claim.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @claim.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= unless !@claim.claim_classifier.nil? then '<none>' else @claim.claim_classifier.name end %>
</p>

<p>
  <strong>Address:</strong>
  <%= @claim.address %>
</p>

<p>
  <strong>Pos lat:</strong>
  <%= @claim.pos_lat %>
</p>

<p>
  <strong>Pos lon:</strong>
  <%= @claim.pos_lon %>
</p>

<p>
  <strong>Pos alt:</strong>
  <%= @claim.pos_alt %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @claim.created_at %>
</p>

<p>
  <strong>Registered at:</strong>
  <%= @claim.registered_at %>
</p>

<p>
  <strong>Registration no:</strong>
  <%= @claim.registration_no %>
</p>

<p>
  <strong>Status:</strong>
  <%= @claim.status %>
</p>
<p>
  <strong>Status code:</strong>
  <%= @claim.status_code %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @claim.deadline %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @claim.user_rate %>
</p>

<p>
  <strong>Authority response:</strong>
  <%= @claim.authority_response %>
</p>

<p>
  <strong>Authority response date:</strong>
  <%= @claim.authority_response_date %>
</p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>